
(add-to-list 'load-path "~/.emacs.d/modules")

(require 'package-module)

;; modules

(require 'global-module)
(require 'fundamental-module)
(require 'fonts-module)
(require 'appearance-module)
(require 'git-module)
(require 'paredit-module)
(require 'electric-pair-module)
(require 'smart-mode-line-module)
(require 'scheme-module)
(require 'erlang-module)
(require 'clojure-module)
(require 'sml-module)
(require 'haskell-module)
(require 'elm-module)
(require 'elisp-module)
(require 'lisp-module)
(require 'lua-module)
(require 'javascript-module)
(require 'xml-module)
(require 'racket-module)
(require 'snippets-module)
(require 'themes-module)
(require 'flycheck-module)
(require 'user-module)
